name: Go Build & Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build the project
        run: go build ./...

      - name: Run tests with gotestsum and coverage
        run: |
          gotestsum --format=standard-verbose -- -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.out
